import type { Metadata } from 'next'
import './globals.css'
import { Sofia_Sans } from 'next/font/google'

const Sofia = Sofia_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body className={Sofia.className}>{children}</body>
    </html>
  )
}
